# Generated by Django 2.2.4 on 2019-09-09 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 13, 25, 11, 576243, tzinfo=utc)),
        ),
    ]
