# Generated by Django 2.2.4 on 2019-09-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20190909_0310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
